version: '3.6'
services:
  omeroserver:
    ports:
    - '4064:4064'
    env_file:
    - omero.prod.env
    volumes:
    - '/hybrid_omero/omero:/OMERO'
    - './var-server:/opt/omero/web/OMERO.server/var-server/'
  omeroweb:
    ports:
    - '127.0.0.1:4080:4080'
    env_file:
    - omero.prod.env
    volumes:
    - './var-web:/opt/omero/web/OMERO.web/var-web/'
